### ISSUE TITLE
got a crash on android R

### ISSUE THREAD

**Issue by yuan0818** [google/mobly-snippet-lib#107]
_**here is the crash info**_ 
08-20 05:18:06.796  5560  5582 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/test/suitebuilder/annotation/Suppress;
08-20 05:18:06.796  5560  5582 E AndroidRuntime:        at android.support.test.internal.runner.TestRequestBuilder.<init>(TestRequestBuilder.java:83)
08-20 05:18:06.796  5560  5582 E AndroidRuntime:        at android.support.test.internal.runner.TestRequestBuilder.<init>(TestRequestBuilder.java:546)
08-20 05:18:06.796  5560  5582 E AndroidRuntime:        at android.support.test.runner.AndroidJUnitRunner.createTestRequestBuilder(AndroidJUnitRunner.java:501)
08-20 05:18:06.796  5560  5582 E AndroidRuntime:        at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:476)
08-20 05:18:06.796  5560  5582 E AndroidRuntime:        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:373)
08-20 05:18:06.796  5560  5582 E AndroidRuntime:        at com.google.android.mobly.snippet.SnippetRunner.onStart(SnippetRunner.java:133)
08-20 05:18:06.796  5560  5582 E AndroidRuntime:        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)

**I traced the full method call stack and seeked  some Info about _android.test.suitebuilder.annotation.Suppress_,  the module _android.test_ has been removed in API LEVEL 28,  I'am  an backend developer shot of android application development, so, I wanna get some help on how make it work on Android 28+**

**Comment by xpconanfan** [comment]
Thanks for reporting. We'll take a look

**Comment by xianyuanjia** [comment]
Given that the stacktrace shows `android.support.test` and not `androidx.test`, I believe this is due to the current snippet version still using the deprecated  `android.support.test` library. This should have been addressed by PR #101, and is pending a new release.
