### ISSUE TITLE
Better error message for when specified snippet class does not exist

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly-snippet-lib#30]
If the snippet manifest's meta-data has classes that don't exist, say:

```xml
    <meta-data
        android:name="mobly-snippets"
        android:value="com.my.snippet.DoesNotExist" />
```

Snippet simply crashes on launching with no proper error message:
```
$ snippet_shell.py com.my.snippetINFO:root:Stopping snippet apk with: am instrument -w -e action stop com.my.snippet/com.google.android.mobly.snippet.SnippetRunner
INFO:root:Launching snippet apk with: am instrument -e action start -e port 3429 com.my.snippet/com.google.android.mobly.snippet.SnippetRunner
Traceback (most recent call last):
  File "/usr/local/bin/snippet_shell.py", line 10, in <module>
    execfile(__file__)
  File "/usr/local/google/home/angli/Developer/mobly/tools/snippet_shell.py", line 65, in <module>
    SnippetShell(args.package[0]).main(args.serial)
  File "/usr/local/google/home/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 86, in main
    self.start_console()
  File "/usr/local/google/home/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 71, in start_console
    self._start_services(console_env)
  File "/usr/local/google/home/angli/Developer/mobly/tools/snippet_shell.py", line 42, in _start_services
    self._ad.load_snippet(name='snippet', package=self._package)
  File "/usr/local/google/home/angli/Developer/mobly/mobly/controllers/android_device.py", line 566, in load_snippet
    self._start_jsonrpc_client(client, host_port, device_port)
  File "/usr/local/google/home/angli/Developer/mobly/mobly/controllers/android_device.py", line 608, in _start_jsonrpc_client
    client.connect(port=host_port)
  File "/usr/local/google/home/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 212, in connect
    resp = self._cmd(cmd, uid)
  File "/usr/local/google/home/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 242, in _cmd
    return self._client.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer
```

**Comment by dthkao** [comment]
I see a different error but same root cause:
```
INFO:root:Stopping snippet apk with: am instrument -w -e action stop com.google.android.apps.dialer.acts.utils.ui.app/com.google.android.mobly.snippet.SnippetRunner
INFO:root:Launching snippet apk with: am instrument -e action start -e port 9795 com.google.android.apps.dialer.acts.utils.ui.app/com.google.android.mobly.snippet.SnippetRunner
Traceback (most recent call last):
  File "third_party/py/mobly/tools/snippet_shell.py", line 66, in <module>
    SnippetShell(args.package[0]).main(args.serial)
  File "/google/src/cloud/davidkao/dialer_switch/google3/third_party/py/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 86, in main
    self.start_console()
  File "/google/src/cloud/davidkao/dialer_switch/google3/third_party/py/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 71, in start_console
    self._start_services(console_env)
  File "third_party/py/mobly/tools/snippet_shell.py", line 43, in _start_services
    self._ad.load_snippet(name='snippet', package=self._package)
  File "/google/src/cloud/davidkao/dialer_switch/google3/third_party/py/mobly/controllers/android_device.py", line 565, in load_snippet
    self._start_jsonrpc_client(client)
  File "/google/src/cloud/davidkao/dialer_switch/google3/third_party/py/mobly/controllers/android_device.py", line 606, in _start_jsonrpc_client
    client.start_app()
  File "/google/src/cloud/davidkao/dialer_switch/google3/third_party/py/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 175, in start_app
    '%s failed to start on %s.' % (self.app_name, self._adb.serial))
mobly.controllers.android_device_lib.jsonrpc_client_base.AppStartError: com.google.android.apps.dialer.acts.utils.ui.app failed to start on <serial>.
```

**Comment by dthkao** [comment]
I see a different error but same root cause:
`mobly.controllers.android_device_lib.jsonrpc_client_base.AppStartError: com.package.name failed to start on <serial>.`

**Comment by xpconanfan** [comment]
After the client change, a class does not exist error on the server side causes the client to hang.
